In [4]:
import altair as alt
from vega_datasets import data

df = data.cars()

In [5]:
df.head()

,Acceleration,Cylinders,Displacement,Horsepower,Miles_per_Gallon,Name,Origin,Weight_in_lbs,Year
0,12.0,8,307.0,130.0,18.0,chevrolet chevelle malibu,USA,3504,1970-01-01
1,11.5,8,350.0,165.0,15.0,buick skylark 320,USA,3693,1970-01-01
2,11.0,8,318.0,150.0,18.0,plymouth satellite,USA,3436,1970-01-01
3,12.0,8,304.0,150.0,16.0,amc rebel sst,USA,3433,1970-01-01
4,10.5,8,302.0,140.0,17.0,ford torino,USA,3449,1970-01-01

In [12]:
df1 = df.query("Origin == 'USA' and Cylinders == 8")

In [13]:
df1

,Acceleration,Cylinders,Displacement,Horsepower,Miles_per_Gallon,Name,Origin,Weight_in_lbs,Year
0,12.0,8,307.0,130.0,18.0,chevrolet chevelle malibu,USA,3504,1970-01-01
1,11.5,8,350.0,165.0,15.0,buick skylark 320,USA,3693,1970-01-01
2,11.0,8,318.0,150.0,18.0,plymouth satellite,USA,3436,1970-01-01
3,12.0,8,304.0,150.0,16.0,amc rebel sst,USA,3433,1970-01-01
4,10.5,8,302.0,140.0,17.0,ford torino,USA,3449,1970-01-01
5,10.0,8,429.0,198.0,15.0,ford galaxie 500,USA,4341,1970-01-01
6,9.0,8,454.0,220.0,14.0,chevrolet impala,USA,4354,1970-01-01
7,8.5,8,440.0,215.0,14.0,plymouth fury iii,USA,4312,1970-01-01
8,10.0,8,455.0,225.0,14.0,pontiac catalina,USA,4425,1970-01-01
9,8.5,8,390.0,190.0,15.0,amc ambassador dpl,USA,3850,1970-01-01
11,11.5,8,350.0,165.0,NaN,chevrolet chevelle concours (sw),USA,4142,1970-01-01
12,11.0,8,351.0,153.0,NaN,ford torino (sw),USA,4034,1970-01-01
13,10.5,8,383.0,175.0,NaN,plymouth satellite (sw),USA,4166,1970-01-01
14,11.0,8,360.0,175.0,NaN,amc rebel sst (sw),USA,3850,1970-01-01
15,10.0,8,383.0,170.0,15.0,dodge challenger se,USA,3563,1970-01-01
16,8.0,8,340.0,160.0,14.0,plymouth 'cuda 340,USA,3609,1970-01-01
17,8.0,8,302.0,140.0,NaN,ford mustang boss 302,USA,3353,1970-01-01
18,9.5,8,400.0,150.0,15.0,chevrolet monte carlo,USA,3761,1970-01-01
19,10.0,8,455.0,225.0,14.0,buick estate wagon (sw),USA,3086,1970-01-01
31,14.0,8,360.0,215.0,10.0,ford f250,USA,4615,1970-01-01
32,15.0,8,307.0,200.0,10.0,chevy c20,USA,4376,1970-01-01
33,13.5,8,318.0,210.0,11.0,dodge d200,USA,4382,1970-01-01
34,18.5,8,304.0,193.0,9.0,hi 1200d,USA,4732,1970-01-01
45,12.0,8,350.0,165.0,14.0,chevrolet impala,USA,4209,1971-01-01
46,11.5,8,400.0,175.0,14.0,pontiac catalina brougham,USA,4464,1971-01-01
47,13.5,8,351.0,153.0,14.0,ford galaxie 500,USA,4154,1971-01-01
48,13.0,8,318.0,150.0,14.0,plymouth fury iii,USA,4096,1971-01-01
49,11.5,8,383.0,180.0,12.0,dodge monaco (sw),USA,4955,1971-01-01
50,12.0,8,400.0,170.0,13.0,ford country squire (sw),USA,4746,1971-01-01
51,12.0,8,400.0,175.0,13.0,pontiac safari (sw),USA,5140,1971-01-01
...,...,...,...,...,...,...,...,...,...
215,13.2,8,318.0,150.0,13.0,plymouth volare premier v8,USA,3940,1976-01-01
219,12.1,8,350.0,180.0,16.5,cadillac seville,USA,4380,1976-01-01
220,12.0,8,350.0,145.0,13.0,chevy c10,USA,4055,1976-01-01
221,15.0,8,302.0,130.0,13.0,ford f108,USA,3870,1976-01-01
222,14.0,8,318.0,150.0,13.0,dodge d100,USA,3755,1976-01-01
228,12.5,8,305.0,145.0,17.5,chevrolet caprice classic,USA,3880,1977-01-01
229,19.0,8,260.0,110.0,17.0,oldsmobile cutlass supreme,USA,4060,1977-01-01
230,13.7,8,318.0,145.0,15.5,dodge monaco brougham,USA,4140,1977-01-01
231,14.9,8,302.0,130.0,15.0,mercury cougar brougham,USA,4295,1977-01-01
236,11.1,8,400.0,180.0,16.0,pontiac grand prix lj,USA,4220,1977-01-01
237,11.4,8,350.0,170.0,15.5,chevrolet monte carlo landau,USA,4165,1977-01-01
238,12.2,8,400.0,190.0,15.5,chrysler cordoba,USA,4325,1977-01-01
239,14.5,8,351.0,149.0,16.0,ford thunderbird,USA,4335,1977-01-01
256,15.5,8,260.0,110.0,19.9,oldsmobile cutlass salon brougham,USA,3365,1978-01-01
257,13.2,8,318.0,140.0,19.4,dodge diplomat,USA,3735,1978-01-01
258,12.8,8,302.0,139.0,20.2,mercury monarch ghia,USA,3570,1978-01-01
269,13.2,8,305.0,145.0,19.2,chevrolet monte carlo landau,USA,3425,1978-01-01
271,11.2,8,302.0,139.0,18.1,ford futura,USA,3205,1978-01-01
272,13.7,8,318.0,140.0,17.5,dodge magnum xe,USA,4080,1978-01-01
292,15.4,8,305.0,130.0,17.0,chevrolet caprice classic,USA,3840,1979-01-01
293,13.4,8,302.0,129.0,17.6,ford ltd landau,USA,3725,1979-01-01
294,13.2,8,351.0,138.0,16.5,mercury grand marquis,USA,3955,1979-01-01
295,15.2,8,318.0,135.0,18.2,dodge st. regis,USA,3830,1979-01-01
296,14.9,8,350.0,155.0,16.9,buick estate wagon (sw),USA,4360,1979-01-01
297,14.3,8,351.0,142.0,15.5,ford country squire (sw),USA,4054,1979-01-01
298,15.0,8,267.0,125.0,19.2,chevrolet malibu classic (sw),USA,3605,1979-01-01
299,13.0,8,360.0,150.0,18.5,chrysler lebaron town @ country (sw),USA,3940,1979-01-01
305,17.4,8,350.0,125.0,23.0,cadillac eldorado,USA,3900,1979-01-01
307,22.2,8,260.0,90.0,23.9,oldsmobile cutlass salon brougham,USA,3420,1979-01-01
372,19.0,8,350.0,105.0,26.6,oldsmobile cutlass ls,USA,3725,1982-01-01